; ******************************************************************************
; ******************************************************************************
;
;		Name : 		loadcode.asm
;		Purpose : 	Load Code into BASIC space for testing
;		Author : 	Paul Robson (paul@robsons.org.uk)
;		Created : 	27th October 2019
;
; ******************************************************************************
; ******************************************************************************

; ******************************************************************************
;
;		Simple Block copy of test program -> $801. Not in final build.
;
; ******************************************************************************

LoadBasicCode:
		set16 	zTemp0,LBCTest
		set16 	zTemp1,$801
_LBCCopy:
		ldy 	#2							; skip over the loading address
		lda 	(zTemp0),y 					; skips first two bytes :)
		sta 	(zTemp1)
		inc16	zTemp0
		inc16 	zTemp1
		lda 	zTemp0
		cmp 	#LBCTestEnd & $FF
		bne 	_LBCCopy
		lda 	zTemp0+1
		cmp 	#LBCTestEnd >> 8
		bne 	_LBCCopy
		rts
		;
		;		This is generated by makeprogram.py
		;
LBCTest:
		.binary 	"../generated/test.prg"
LBCTestEnd:		
